<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-0BNEF2JS" name="verifytext" tests="1" failures="0" timestamp="13 Jun 2020 07:17:14 GMT" time="0.052" errors="0">
  <testcase name="@BeforeTest before" time="0.0" classname="Academy.verifytext">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at resource.base.initializedriver(base.java:34)
	at Academy.verifytext.before(verifytext.java:26)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest before -->
  <testcase name="@AfterTest after" time="0.0" classname="Academy.verifytext">
    <skipped/>
  </testcase> <!-- @AfterTest after -->
  <testcase name="initializehomepage" time="0.004" classname="Academy.verifytext">
    <skipped/>
  </testcase> <!-- initializehomepage -->
</testsuite> <!-- verifytext -->
